function name = build_1cone_filename(conerun, stimrun, conergc)
parseconeprefix = parse_rrs_prefix(conerun);
parserunprefix = parse_rrs_prefix(stimrun);
if iscell(conergc), conergc = conergc{1}; end
celltype = conerun.cell_types{find_cell_types(conerun, conergc)}.name;
name = sprintf('%s_%s_%s_f%02.fid%d',    ...
    parserunprefix.piece_fullname,          ...
    parserunprefix.run_full_name,           ...
    strrep(celltype, ' ', ''),              ...
    parseconeprefix.run_num,                ...
    conergc);