function [eiscaledowner eiscaleupper] = add_ei_scale_spinner(fig, position)
eiscaledowner = uicontrol(fig, ...
    'Style'   , 'pushbutton',      ...
    'String'  , '<',               ...
    'FontSize', 12,                ...
    'Units'   , 'normalized',      ...
    'Callback', @eiscaleup         ...
);
if nargin > 1, 
    if length(position) == 2, position(3:4) = [1 1]; end
    set(eiscaledowner, 'Position', position); 
end
fit_uicontrol_to_text(eiscaledowner);
setappdata(fig, 'eiscaledowner', eiscaledowner);

pos = get(eiscaledowner, 'Position');
eiscaleupper = uicontrol(fig, ...
    'Style'   , 'pushbutton',                                        ...
    'String'  , '>',                                                 ...
    'FontSize', get(eiscaledowner, 'FontSize'),                      ...
    'Units'   , get(eiscaledowner, 'Units'),                         ...
    'Position', get(eiscaledowner, 'Position') + [pos(3)*1.1 0 0 0], ...
    'Callback', @eiscaledown                                         ...
);
setappdata(fig, 'eiscaleupper', eiscaleupper);


function changescale(h,delta)
fig = getfig(h);
params = getappdata(fig, 'params');
params.scale = params.scale + delta;
setappdata(fig, 'params', params);

slider = getappdata(fig, 'ei_slider');
api = getappdata(fig, 'api');
api.slider_plot(slider,[]);

function eiscaledown(h,~)
changescale(h,-1);

function eiscaleup(h,~)
changescale(h,1);