function [fit_params, params] = compute_snls(spikes, gen_signals, varargin)
% compute_snl     Compute static nonlinearity and fit
%
%  NOTE: this code only supports white noise movies generated by obvius
%
% usage:  [fit_params,gen_signals,params] = compute_snls(strfs, spikes, movie, <params>)
%
% arguments:    strfs - cell array, each element a YxXxCxT matrix specifying STRF for each cell
%              spikes - FxN matrix of spike times, each column a time point, each row a cell
%               movie - java object of stimulus movie
%            <params> - struct or list of optional parameters (see below)
%
% outputs:  
%
%     NOTE: each of these output variables is a cell array/matrix,
%               each element/column corresponding to one neuron
%
%          fit_params{cc} - fit parameters
%
%
%
% optional params, their default values, and what they specify:
%
% fit           'exp'                     	what kind of fit
%                                               'exp' - exponential, exp(b + a*g)
%
% 2009-09  gauthier
% 
% Modified by Suva Roy 09/14/2017


% SET UP OPTIONAL ARGUMENTS
p = inputParser;
p.addParameter('fit','exp', @(x)any(strcmpi(x,{'exp','cum_norm'})));

p.parse(varargin{:});
params = p.Results;


% FIT NONLINEARITY

% initialize storage variable
num_cells = size(gen_signals, 2);
fit_params = cell(num_cells, 1);
%optimization_options = optimoptions('fminunc', 'MaxFunctionEvaluations', 1000);  %  Default:  modified by Suva Roy (09/14/2017) 
optimization_options = optimset('MaxFunEvals', 500); % Using default funtol and steptol


% cycle through each cell
for cc = 1:num_cells

    switch params.fit
        case 'exp'

            % get spike times
            % if there are N spikes per bin, list that bin N times
            spike_times = [];
            for nn = 1:full(max(spikes(:,cc)))
                spike_times = [spike_times; find( spikes(:,cc)>(nn-1) )];
            end

            % define function that gives likelihood
            L = @(x)identify_SNL_scalars_fn(x,spike_times,gen_signals(:,cc));

            % turn gradient on
            %options = optimset('GradObj','on'); % optimset has been
                                                %depricated by matlab: GDF 7/10/2017

            % identify best a and b
            [fit, temp_fval, temp_exitflag] = fminunc(L,[0 0],optimization_options);

            fit_params{cc}.a = fit(1);
            fit_params{cc}.b = fit(2);
            fit_params{cc}.type = params.fit;
            fit_params{cc}.fval = temp_fval;
            fit_params{cc}.exitflag = temp_exitflag;



            case 'cum_norm'

            % define function that gives rmse
            rmse = @(x)identify_SNL_scalars_fn_cum_norm(x,spikes(:,cc),gen_signals(:,cc));

            % get raw gen_signal vs mean_spk_rate 
            [X,Y] = curve_from_binning(gen_signals(:,cc),spikes(:,cc),'average_y','mean','average_x','mean');

            % identify best a and b
            %[fit, temp_fval, temp_exitflag] = fminunc(rmse,[2 1 0.5], optimization_options);
            [fit, temp_fval, temp_exitflag] = fminsearch(rmse, [2 1 0.5], optimization_options); % modified by Suva Roy 09/14/2017

            fit_params{cc}.a = fit(1);
            fit_params{cc}.b = fit(2);
            fit_params{cc}.c = fit(3);
            fit_params{cc}.type = params.fit;
            fit_params{cc}.fval = temp_fval;
            fit_params{cc}.exitflag = temp_exitflag;
            fit_params{cc}.mean_gen_signal = X;
            fit_params{cc}.mean_spk_rate = Y;

    end

end




function [L,g] = identify_SNL_scalars_fn(x,spike_times,gen_signal)

% likelihood
L =  length(spike_times)*x(2) + x(1)*sum(gen_signal(spike_times)) - ...
    exp(x(2))*sum(exp(x(1)*gen_signal))  ;
% gradient
if nargout > 1
    g(1) = sum(gen_signal(spike_times)) - exp(x(2))*sum(gen_signal.*exp(x(1)*gen_signal));
    g(2) = length(spike_times) - exp(x(2))*sum(exp(x(1)*gen_signal));
    g = -g;
end

L = -L;

function rmse = identify_SNL_scalars_fn_cum_norm(x,spikes,gen_signal)

[X,Y] = curve_from_binning(gen_signal,spikes,'average_y','mean','average_x','mean');

% rmse  
mean_rates = x(1) * normcdf(x(2)*X - x(3), 0, 1);
rmse = sqrt(mean((Y - mean_rates).^2));


