function [b1,b3,list1,list2] = loop_slider_2(k,kmin,kmax,list1,list2)
% see loop_slider_list
%
%greschner


b1= uicontrol(gcf,...
    'Style','slider',...
    'Min' ,kmin(1),'Max',kmax(1), ...
    'Units','normalized', ...
    'Position',[0,0,.6,.03], ...
    'Value', k(1),...
    'SliderStep',[1/(kmax(1)-kmin(1)) 1/(kmax(1)-kmin(1))],...
    'CallBack', 'uiresume;');

b2 = uicontrol('Style','pushbutton', ...
    'Units','normalized', ...
    'Position',[0.61 0 .05 .03], ...
    'String','',...
    'Callback','list1=[list1 k(1)]; uiresume;');

b3= uicontrol(gcf,...
    'Style','slider',...
    'Min' ,kmin(2),'Max',kmax(2), ...
    'Units','normalized', ...
    'Position',[0,.03,.6,.03], ...
    'Value', k(2),...
    'SliderStep',[1/(kmax(2)-kmin(2)) 1/(kmax(2)-kmin(2))],...
    'CallBack', 'uiresume;');

b4 = uicontrol('Style','pushbutton', ...
    'Units','normalized', ...
    'Position',[0.61 .03 .05 .03], ...
    'String','',...
    'Callback','list2=[list2 k(2)]; uiresume;');

