function stimulus = stimulus_from_java_stas(java_stas)
% stimulus_from_java_stas     get stimulus information from an rrs STA file
%
% usage:  stimulus = stimulus_from_java_stas(java_stas)
%
% arguments:  java_stas - java object generated by edu.ucsc.neurobiology.vision.io.STAFile(<sta_file_path>)
%
% outputs:     stimulus - struct with the following fields
%
% stimulus.field_height     # of stixels top to bottom
% stimulus.field_width      # of stixels left to right
% stimulus.interval         # of monitor updates per stimulus refresh
% stimulus.independent      'nil' if r = g = b, 't' if r, g, & b are independent
%
%
% gauthier 2008-03
%


% assume monitor_refresh_rate is 120 Hz
% in the future, there should be a separate place to specify this so that it can vary
monitor_refresh_rate = 120;  % Hz


% refresh interval
stimulus.interval = round(java_stas.getRefreshTime * monitor_refresh_rate / 1000);


% X and Y size
stimulus.field_height = java_stas.getHeight;
stimulus.field_width = java_stas.getWidth;


% determine whether triplets of each frame buffer are identical in one example cell

% load one cell's STA
sta_cell_ids = java_stas.getIDList;
buff = java_stas.getSTA(sta_cell_ids(1)).getFrame(1).getBuffer;

% check the first two stixels
if (buff(1) == buff(2)) && (buff(2) == buff(3)) && ...
        (buff(4) == buff(5)) && (buff(5) == buff(6))

    % if the R, G, & B values are exactly equal, assume this holds for all stixels
    stimulus.independent = 'nil';
else
    
    % otherwise, assume they can vary
    stimulus.independent = 't';
end
