function Responses=NS512_ApplyLinearArtifactModel(DataPath,PatternNumber,Movies,GoodChannels,TracesNumberLimit,EventNumber,ClusterFileName,NS_GlobalConstants);
%DataChannels - data for which channels are saved in the files generated by
%the preprocessing procedure
%GoodChannels - which channels from the DataChannels are of interest for
%the analysis. Values of GoodChannels are simply indexes for the
%DataChannels array.
%StimChannels - responses to stumulation of this channels are of interest
%StChannels - channels stimulated by given pattern

%NS_GlobalConstants=NS_GenerateGlobalConstants(61);
currentRanges = NS_GlobalConstants.CurrentRanges;
StimChannels=[1:512];

Amplitudes=Movies;

Amplitudes(1)=NS_StimulationAmplitude(DataPath,PatternNumber,Movies(1),StimChannels,NS_GlobalConstants);
[DataTraces,ArtifactDataTraces,Channels]=NS_ReadPreprocessedData(DataPath,DataPath,0,PatternNumber,Movies(1),0,0);
Art1=mean(DataTraces);

Amplitudes(2)=NS_StimulationAmplitude(DataPath,PatternNumber,Movies(2),StimChannels,NS_GlobalConstants);
if Amplitudes(2)==Amplitudes(1)
    error('The first two amplititudes are identical')
end
[DataTraces,ArtifactDataTraces,Channels]=NS_ReadPreprocessedData(DataPath,DataPath,0,PatternNumber,Movies(2),0,0);
Art2=mean(DataTraces);

A1=Amplitudes(1);
A2=Amplitudes(2);

Samples=[13:60];
Threshold=15;

Responses=[];

for i=3:length(Movies)   
    MovieNumber=Movies(i);
    [DataTraces,ArtifactDataTraces,DataChannels]=NS_ReadPreprocessedData(DataPath,DataPath,0,PatternNumber,MovieNumber,0,0);    
    clear ArtifactDataTraces;
    SD=size(DataTraces);
    DataTracesFinal=zeros(SD(1),SD(2),SD(3));
    
    [StChannels,Amplitudes]=NS_StimulatedChannels(DataPath,PatternNumber,MovieNumber,StimChannels,NS_GlobalConstants);
    A=max(Amplitudes);
    %a=A2;
    %b=A1;
    Art=Art2+(A-A2)/(A2-A1)*(Art2-Art1);
    
    for j=1:SD(1)
        DataTracesFinal(j,:,:)=DataTraces(j,:,:)-Art;                   
    end         
    
    FigureProperties=struct('FigureNumber',12,'Subplot',[2 3 3],'TimeRange',[0 65],'AmplitudeRange',[-30 30],'FontSize',16,'Colors',['k' 'r' 'b' 'm' 'g' 'c' 'y'],'LineWidth',1,'YLabel','signal [mV]');
    WaveformTypes=ones(1,SD(1));
    
    if A~=A2        
        Art1Old=Art1; %just for tests!!
        Art2Old=Art2;
        A1=A2;
        A2=A;        
        Art1=Art2;        
        Art2=mean(DataTraces);
    end        
    clear DataTraces;
    
    %channels     
    GoodChannels2=NS_RemoveBadChannels(DataChannels(GoodChannels),StChannels); %this are real channels
    ChannelsToAnalyze=[];
    for j=1:length(DataChannels)
        if find(GoodChannels2==DataChannels(j))
            ChannelsToAnalyze=[ChannelsToAnalyze j];
        end
    end
    
    x=DataTracesFinal(:,ChannelsToAnalyze,Samples);
    clear DataTracesFinal;
    Sx=size(x);
    wavs=zeros(Sx(1),Sx(3));
    %figure(1);
    for j=1:0 %Sx(2)
        wavs(:,:)=x(:,j,:);        
        subplot(8,10,j);
        plot(wavs');
        axis([0 40 -20 20]);
    end
    %pause(0.5)
    %y=NS_PlotClustersOfSignaturesOnArrayLayout(x,GoodChannels2,WaveformTypes,1,FigureProperties,NS_GlobalConstants);

    [mins,indexes]=min(x,[],3);    
    [Events,Electrodes]=find(mins<-Threshold);    

    Counts=histc(Electrodes,[1:512]);
            
    EventsFinal=unique(Events); %so each event is count only once, even if the spike exceeds threshold on more than opne electrode
    
    if length(EventsFinal)>10
    PN=PatternNumber;
    MN=MovieNumber
    ilosc=length(EventsFinal)
    elektrody=unique(ChannelsToAnalyze(Electrodes))
    wavs=zeros(Sx(1),Sx(3));
    wavs(:,:)=x(:,Electrodes(1),:);
    size(wavs)
    figure(1)
    plot(wavs')
    
        
    BestElectrodes=GoodChannels2(find(Counts==max(Counts)));
    PrimaryRecordingElectrode=BestElectrodes(1);
    ElectrodesFinal=GoodChannels2(unique(Electrodes));
    WaveformTypes=ones(1,SD(1));
    Responses=[PatternNumber MovieNumber PrimaryRecordingElectrode];
    %Responses=[Responses a];
        %smins=size(mins)
        %sev=size(event)        
        %PatternNumber

        %electrodes=GoodChannels2(unique(electrode))
        %ElNumber=50;
        %b=reshape(DataTracesFinal(:,electrodes(1),Samples),SD(1),length(Samples));
        %b=reshape(DataTracesFinal(:,ElNumber,Samples),SD(1),length(Samples));

        %figure(1);
        %plot(b');
        %axis([0 70 -240 240]);
        %grid on;
        
        %figure(2);
        %size(Art1)
        %size(Art2)
        %nn=Art1Old(1,ElNumber,Samples);        
        %size(nn)
        %plot(reshape(nn,1,length(Samples)));
        
        %figure(3);
        %nn=Art2Old(1,ElNumber,Samples);        
        %size(nn)
        %plot(reshape(nn,1,length(Samples)));        
        
        %pause(1);          
                
        WaveformTypes(EventsFinal)=2;
        header=NS_SaveClusterFile(ClusterFileName,PatternNumber,Movies(i),WaveformTypes);
        break;
    end        
        %pause(3);
end