function [D2X,D2Y,D2Z]=NS_EstimatePotentialSecondDev(Amplitudes,elX,elY,elZ,x0,y0,z0);
%The function calcuates the total gradient of potential field generated by several
%point sources of current.
%Amplitudes - amplitude for each point source
%elX, elY, elZ - coordinates of the point sources 
%x0,y0,z0 - coordinates of the point where the gradient should be estimated

%ArrayID=1; %61-channel
%electrodeMap=edu.ucsc.neurobiology.vision.electrodemap.ElectrodeMapFactory.getElectrodeMap(ArrayID)
%for i=1:length(electrodes)
%    elX(i)=electrodeMap.getXPosition(electrodes(i));
%    elY(i)=electrodeMap.getYPosition(electrodes(i));
%end
D2X=0;
D2Y=0;
D2Z=0;
G=zeros(1,length(Amplitudes));
D2x=G;
D2y=G;
D2z=G;
for i=1:length(Amplitudes)
    G(i)=2*Amplitudes(i)/((elX(i)-x0)^2+(elY(i)-y0)^2+(elZ(i)-z0^2))^3/2*1e5; %absolute value
    Glength=sqrt((elX(i)-x0)^2+(elY(i)-y0)^2+(elZ(i)-z0)^2);
    D2x(i)=G(i)*(elX(i)-x0)/Glength;
    D2y(i)=G(i)*(elY(i)-y0)/Glength;
    D2z(i)=G(i)*z0/Glength;
    D2X=D2X+D2x(i);
    D2Y=D2Y+D2y(i);
    D2Z=D2Z+D2z(i);
end

%Grad=sqrt(GX^2+GY^2+GZ^2);